### ISSUE TITLE
Variable not bound during evaluation

### ISSUE THREAD

**Issue by brendanzab** [brendanzab/pikelet#22]
Found during [a demo](https://www.meetup.com/Melbourne-Haskell-Users-Group/events/248041735/) at the Melbourne Haskell User Group:

```
Pikelet> (\(t : Type) (f : (a : Type) -> a -> a) => f t) String (\(a : Type) (x : a) => x)
error: internal compiler error: cannot find `t$1` in scope
- <repl>:1:46: not found in this scope
```

If we manually apply the first argument it seems to be fine:

```
Pikelet> (\(f : (a : Type) -> a -> a) => f String) (\(a : Type) (x : a) => x)
\x$12 : #String => x$12 : ($7 : #String) -> #String
```

Thanks @andykitchen for finding this!

**Comment by brendanzab** [comment]
At the moment it doesn't ICE anymore, but gives:

```
Pikelet> (\(t : Type) (f : (a : Type) -> a -> a) => f t) String (\(a : Type) (x : a) => x)
\x$6 : t$1 => x$6 : ($0 : #String) -> #String
```

`t$1` is problematic here - it's escaped out of its context without being substituted away.

**Comment by brendanzab** [comment]
Here is a slightly reduced example:

```
Pikelet> (\(t : Type) (f : (a : Type) -> Type) => f t) String (\(a : Type) => a)
t$32 : Type
```

**Comment by mikeday** [comment]
Even dropping the second argument seems sufficient to go wrong:
```
Pikelet> (\(t: String) (f: String -> String) => f t) "hello"
\(f$57 : String -> String) => f$57 t$56 : (String -> String) -> String
```
presumably t$56 should be "hello"

**Comment by brendanzab** [comment]
Yup, you're right!

**Comment by brendanzab** [comment]
I'm thinking that this might require something like the `let` rule in ΣΠ's β-reduction rules:

<img width="695" alt="screen shot 2018-04-17 at 10 36 39 pm" src="https://user-images.githubusercontent.com/695077/38870151-48997f3c-4290-11e8-85ed-691aefbeb844.png">

Note how:

- The application rule converts applications into let bindings
- The let rule 'pushes' bindings into lambdas, 'capturing' them

At the moment I'm just pushing them onto the existing context (ie. to the left of the turnstile). This means I never actually capture bindings in the closure. 🤔

**Comment by brendanzab** [comment]
Rereading the section of [the ΣΠ paper](https://www.andres-loeh.de/PiSigma/PiSigma.pdf) on β-reduction, I've now discovered that I have a name for what I've been trying to do. It's an '[explicit substitution calculus](https://en.wikipedia.org/wiki/Explicit_substitution)'!

**Comment by brendanzab** [comment]
Interesting thread on the twitterverse: https://twitter.com/brendanzab/status/987946437508919296
