### ISSUE TITLE
Variable numbering doesn't reset

### ISSUE THREAD

**Issue by markbrown** [brendanzab/pikelet#6]
Each time a term is printed in the REPL the variable numbering is different. It looks like the variable numbers don't reset at any time. This is confusing if you enter the same or similar term twice and expect to get the same or similar output.

**Comment by brendanzab** [comment]
Yup, I use [an atomic](https://github.com/brendanzab/nameless/blob/f9a8ab17e9bde6f72e3c2143edcb93ea03f0c367/nameless/src/name.rs#L31-L41) for the fresh variable generation in nameless. Ideally I'd want to do some deterministic renaming when pretty printing, and try to use the name hint in the generated variables if possible. At the moment I'm printing the core terms directly, but I'm thinking I'd like to convert them [back into renamed concrete terms](https://github.com/brendanzab/pikelet/blob/master/src/syntax/translation/core_to_concrete.rs#L144-L190) first, then pretty print those.

**Comment by brendanzab** [comment]
Closing in favor of #36
